"use client";

import { useMemo, useState } from "react";

type State = "visited" | "mentioned" | "imagined" | "uncertain";
type Item = { id:number; year:number; title:string; zh:string; author:string; place:string; placeZh:string; kind:"Domestic"|"Overseas"; state:State; mobility:string; medium:string; note:string; x:number; y:number };

const works:Item[] = [
  {id:1,year:1983,title:"A Journey Home",zh:"故乡行",author:"Chen Ruqiang",place:"Fuchun River — Xin'an River — Meicheng",placeZh:"浙江富春江—新安江—梅城",kind:"Domestic",state:"visited",mobility:"landscape journey",medium:"Traveller magazine",note:"Early domestic landscape travel.",x:72,y:55},
  {id:2,year:1983,title:"Equatorial Snow in the Andes",zh:"安第斯的赤道雪",author:"Liu Deyou",place:"Ecuador / Andes",placeZh:"厄瓜多尔／安第斯",kind:"Overseas",state:"visited",mobility:"reporting",medium:"People's Daily",note:"Newspaper overseas travel reportage.",x:27,y:68},
  {id:3,year:1998,title:"Notes from Ali I: Seeing Shiquanhe",zh:"阿里纪行系列报道之一：我看狮泉河",author:"Cheng Weidong",place:"Shiquanhe, Ali, Tibet",placeZh:"西藏阿里狮泉河",kind:"Domestic",state:"visited",mobility:"field reporting",medium:"China Tibet",note:"Frontier and plateau reporting.",x:65,y:51},
  {id:4,year:1993,title:"The Blue Lake Baikal",zh:"蓝色的贝加尔湖",author:"Chen Jintian",place:"Lake Baikal, Russia",placeZh:"俄罗斯贝加尔湖",kind:"Overseas",state:"visited",mobility:"reporting",medium:"People's Daily",note:"A post-Cold War northern route.",x:61,y:34},
  {id:5,year:2004,title:"Walking to Motuo: Meaning is Being on the Road",zh:"徒步墨脱：旅途的意义是“在路上”",author:"Annie Baby / Li Jing",place:"Lhasa — Nyingchi — Pai — Motuo",placeZh:"拉萨—林芝—派镇—墨脱",kind:"Domestic",state:"visited",mobility:"walking",medium:"Sanlian Lifeweek",note:"Journey year, not publication year, is mapped here.",x:67,y:54},
  {id:6,year:2009,title:"Antiquities in Libya",zh:"利比亚访古",author:"Zhang Yun",place:"Libya / North Africa",placeZh:"利比亚／北非",kind:"Overseas",state:"uncertain",mobility:"cultural journey",medium:"Bound volume",note:"Precise places await body-level verification.",x:48,y:55},
  {id:7,year:2017,title:"From the Hengduan Mountains to Human Country",zh:"从横断山脉到人域：在川西寻找壮美康巴",author:"Pu Shi",place:"Chengdu — Balang Mountain — Danba",placeZh:"成都—映秀—巴朗山—四姑娘山—丹巴",kind:"Domestic",state:"visited",mobility:"road journey",medium:"Sanlian Lifeweek",note:"Road and mountain movement in western Sichuan.",x:70,y:53},
  {id:8,year:2019,title:"Into Iraq: The Lost Ruins of Babylon",zh:"深入伊拉克，探索两河文明③：失落的巴比伦遗址",author:"Yao Lu",place:"Karbala — Babylon",placeZh:"卡尔巴拉—巴比伦遗址",kind:"Overseas",state:"visited",mobility:"field research",medium:"The Paper",note:"Online travel and archaeological field writing.",x:54,y:51},
  {id:9,year:2024,title:"Wind over the River (excerpt)",zh:"江上有风（节选）",author:"Zhang Qingguo",place:"Daying River, Yunnan",placeZh:"云南西部大盈江／盈江",kind:"Domestic",state:"visited",mobility:"river journey",medium:"People's Literature",note:"Borderland writing in a literary journal.",x:68,y:57},
  {id:10,year:2024,title:"Into Dust: Krak des Chevaliers to Damascus",zh:"隐入征尘：从骑士堡到大马士革",author:"Wang Zaitian",place:"Krak des Chevaliers — Damascus",placeZh:"骑士堡—大马士革，叙利亚",kind:"Overseas",state:"visited",mobility:"cross-border reporting",medium:"Southern Weekly",note:"Contemporary cross-border longform reporting.",x:53,y:52}
];
const states:State[]=["visited","mentioned","imagined","uncertain"];
const stateLabel:Record<State,string>={visited:"visited",mentioned:"mentioned",imagined:"imagined / compared",uncertain:"uncertain"};

export default function Home(){
  const [zh,setZh]=useState(false); const [year,setYear]=useState(2024); const [scope,setScope]=useState<"All"|Item["kind"]>("All"); const [active,setActive]=useState<Item>(works[8]);
  const decade=Math.floor(year/10)*10; const visible=useMemo(()=>works.filter(w=>Math.floor(w.year/10)*10===decade&&(scope==="All"||w.kind===scope)),[decade,scope]);
  const tx=(en:string,cn:string)=>zh?cn:en; const grouped=states.map(s=>({s,items:works.filter(w=>w.place===active.place&&w.state===s)}));
  return <main>
    <nav className="topbar"><a className="mark" href="#top"><span>W</span>CTW</a><div className="navlinks"><a href="#map">{tx("Map","地图")}</a><a href="#reading">{tx("Reading the map","阅读地图")}</a><a href="#methods">{tx("Methods & limits","方法与限制")}</a><button onClick={()=>setZh(!zh)}>{zh?"EN":"中文"}</button></div></nav>
    <section id="top" className="hero"><p className="eyebrow">{tx("Research archive","研究档案")} · 1980—2025</p><h1>{tx("Where Chinese-Language Travel Writing Goes","中文旅行写作去往何处")}</h1><p className="hero-sub">{tx("Place, mobility, and cultural imagination, 1980–2025","地点、移动与文化想象，1980—2025")}</p><p className="hero-intro">{tx("A research archive tracing where Chinese travel writing goes, what it makes visible, and how it imagines places at home and abroad.","一个追踪中文旅行写作去向、可见性与国内外地方想象的研究档案。")}</p><a className="text-link" href="#map">{tx("Explore the archive","进入档案")} <span>↓</span></a><div className="hero-rule"><span>CHINESE-ORIGINAL TRAVEL WRITING</span><span>PLACE / MOBILITY / IMAGINATION</span><span>VERSION 0.1</span></div></section>
    <section id="map" className="map-section"><header className="section-head"><div><p className="eyebrow">01 / {tx("Current view","当前视图")}</p><h2>{tx("A changing geography of attention","不断变化的地方可见性")}</h2></div><p>{tx("The collection is in progress","语料仍在建设中")}<br/><strong>{works.length} {tx("sample records currently shown","当前展示的样本记录")}</strong></p></header>
      <div className="map-shell"><aside className="controls"><div className="control-block"><p>{tx("Decade","十年")}</p><div className="decades">{[1980,1990,2000,2010,2020].map(d=><button className={d===decade?"active":""} key={d} onClick={()=>setYear(d+4)}>{String(d).slice(0,4)}</button>)}</div></div><div className="control-block"><p>{tx("Year","年份")} <output>{year}</output></p><input aria-label="Choose year" type="range" min="1980" max="2025" value={year} onChange={e=>setYear(+e.target.value)}/><div className="range-label"><span>1980</span><span>2025</span></div></div><div className="control-block"><p>{tx("Scope","范围")}</p>{(["All","Domestic","Overseas"] as const).map(v=><button className={`filter ${scope===v?"selected":""}`} key={v} onClick={()=>setScope(v)}>{v==="All"?tx("All places","全部地点"):v==="Domestic"?tx("Domestic","国内"):tx("Overseas","海外")}</button>)}</div><div className="legend">{states.map(s=><span className={s} key={s}>{stateLabel[s]}</span>)}</div></aside>
      <div className="map-canvas"><svg viewBox="0 0 100 68" role="img" aria-label="Interactive research map"><path className="land" d="M4 16L14 11 24 12 30 19 29 29 22 35 20 46 12 48 6 39 9 29Z M36 10L49 7 64 11 73 16 86 16 94 25 88 33 82 34 76 43 67 41 61 34 51 35 45 29 39 26Z M56 43L66 45 71 55 68 64 61 60 58 52Z M76 47L84 48 90 56 87 65 79 62 75 54Z"/><path className="contour" d="M0 37C14 31 20 42 35 37S57 29 69 37s18 8 31 1M1 50c17-8 30 4 47-3s27-3 51-9M35 5c-5 10 3 15-1 27s5 20 1 34"/>{visible.map(w=><g className="place" key={w.id} onMouseEnter={()=>setActive(w)} onFocus={()=>setActive(w)} onClick={()=>setActive(w)} tabIndex={0} role="button" aria-label={`${w.title}, ${w.place}`}><circle className={`halo ${w.state}`} cx={w.x} cy={w.y} r="2.3"/><circle className={`dot ${w.state}`} cx={w.x} cy={w.y} r=".8"/><text x={w.x+1.7} y={w.y-1.5}>{w.place.split("—")[0].split(",")[0]}</text></g>)}</svg><p className="map-note">{tx("Hover a point to open its archive.","悬停点位即可打开相关档案。")}</p></div>
      <aside className="archive-panel"><p className="eyebrow">{tx("Place archive","地点档案")}</p><h3>{zh?active.placeZh:active.place}</h3><p className="archive-note">{active.note}</p><div className="archive-groups">{grouped.map(({s,items})=><div className={`archive-group ${s}`} key={s}><p>{stateLabel[s]} <span>{items.length}</span></p>{items.map(w=><button key={w.id} onClick={()=>setActive(w)}><b>{zh?w.zh:w.title}</b><small>{w.author} · {w.year}</small></button>)}</div>)}</div></aside></div></section>
    <section id="reading" className="reading-section"><div className="reading-copy"><p className="eyebrow">02 / {tx("Reading the map","阅读地图")}</p><h2>{tx("The map is not a route.","地图不是一条路线。")}</h2><p>{tx("It is a record of recurrent attention: the places Chinese-language writers arrive at, return to, compare, and leave at the edge of vision.","它记录的是反复出现的注意力：中文写作者抵达、重返、比较，或留在视野边缘的地方。")}</p><p>{tx("A point links a text, a moment of publication, a mode of movement, and an editorial medium.","每个点都连接一篇文本、一个发表时刻、一种移动和一种媒介。")}</p></div><div className="metric-list"><div><span>01</span><b>1983—2024</b><p>{tx("Current first-pass time span","当前第一批样本覆盖时间")}</p></div><div><span>02</span><b>Domestic / Overseas</b><p>{tx("A comparison, not a binary hierarchy","一种比较，而非二元等级")}</p></div><div><span>03</span><b>Text → Place</b><p>{tx("The smallest evidentiary relation","最小的证据关系")}</p></div></div></section>
    <section className="field-placeholder"><div><p className="eyebrow">FIELD MATERIAL / TO BE ADDED</p><h2>{tx("Your field materials belong here","你的田野材料留在这里")}</h2><p>{tx("Reserve this space for a photograph, notebook page, or hand-drawn route from your own travels. It will sit beside an evidentiary case, not decorate the interface.","为你的旅行照片、笔记页或手绘路线预留。它将只与有证据支撑的案例并置，而不会成为装饰。")}</p></div><div className="placeholder-frame"><span>PHOTO · NOTEBOOK · MAP FRAGMENT</span><i>+</i></div></section>
    <section id="methods" className="methods"><p className="eyebrow">03 / {tx("Methods & limits","方法与限制")}</p><h2>{tx("The map is provisional by design.","这张地图有意保持暂定性。")}</h2><div className="method-grid"><p>{tx("It distinguishes bibliographic discovery from legally analysable text, and it never turns an unverified lead into a spatial claim.","它区分书目发现与可合法分析的文本，绝不把未核验线索变成空间结论。")}</p><ul><li>Bibliographic pool ≠ full-text corpus</li><li><i>visited</i>, <i>mentioned</i>, <i>imagined / compared</i>, and <i>uncertain</i> remain distinct.</li><li>Only evidence-ready records can enter spatial counts.</li><li>Every pattern must return to close reading.</li></ul></div></section>
    <section className="missing"><p className="eyebrow">04 / {tx("Missing places","未被看见的地方")}</p><h2>{tx("Absence is not an empty map.","缺席不是一张空地图。")}</h2><p>{tx("The empty areas here describe the present collection: gaps in access, publication history, verification, and cultural attention. They are research questions, never proof that a place has not been written.","这里的空白描述的是目前的收藏：获得文本、出版史、核验与文化注意力的缺口。它们是研究问题，而不是某地从未被书写的证明。")}</p></section><footer><span>WHERE CHINESE-LANGUAGE TRAVEL WRITING GOES</span><span>RESEARCH ARCHIVE · 2026</span></footer>
  </main>
}
